export const actionTypes = {
    FETCH_PRODUCTS: "FETCH_PRODUCTS",
    FETCH_PRODUCT_DETAILS: "FETCH_PRODUCT_DETAILS",
    FETCH_CATEGORIES: "FETCH_CATEGORIES",
    FETCH_CART_ITEMS: "FETCH_CART_ITEMS",
    SET_PRODUCT: "SET_PRODUCT",
    SELECTED_PRODUCT: "SELECTED_PRODUCT",
    REMOVE_SELECTED_PRODUCT: "REMOVE_SELECTED_PRODUCT"
}